from django.urls import path

from Homeserviceapp import views

urlpatterns = [
    path('', views.main_view, name='main_view'),
    path('user_registration', views.user_registration, name='user_registration'),
    path('login_view', views.login_view, name='login_view'),
    path('user_dashboard', views.user_dashboard, name='user_dashboard'),
    path('worker_dashboard', views.worker_dashboard, name='worker_dashboard'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('logout_view', views.logout_view, name='logout_view'),
    path('category_add', views.category_add, name='category_add'),
    path('category_view', views.category_view, name='category_view'),
    path('services', views.user_category_view, name='services'),
    path('category_delete/<int:id>/', views.category_delete, name='category_delete'),
    path('worker_registration', views.worker_registration, name='worker_registration'),
    path('view_workers_user', views.view_workers_user, name='view_workers_user'),
    path('view_workers_admin', views.view_workers_admin, name='view_workers_admin'),
    path('worker_delete/<int:id>/', views.worker_delete, name='worker_delete'),
    path('payment_add/<int:id>/', views.update_payment, name='payment_add'),
    path('add_availability', views.add_availability, name='add_availability'),
    path('view_availability', views.view_availability, name='view_availability'),
    path('delete_availability/<int:id>/', views.delete_availability, name='delete_availability'),
    path('update_availability/<int:id>/', views.update_availability, name='update_availability'),
    path('view_worker_availability/<int:id>/', views.view_availability_user, name='view_worker_availability'),
    path('book_appointment/<int:id>/', views.book_appointment, name='book_appointment'),
    path('user_view_appointment', views.user_view_appointments, name='user_view_appointment'),
    path('cancel_appointment/<int:id>/', views.cancel_appointment, name='cancel_appointment'),
    path('admin_view_appointment', views.admin_view_appointment, name='admin_view_appointment'),
    path('approve_appointment/<int:id>/', views.approve_appointment, name='approve_appointment'),
    path('reject_appointment/<int:id>/', views.reject_appointment, name='reject_appointment'),
    path('worker_view_appointment', views.worker_view_appointment, name='worker_view_appointment'),
    path('update_work_status/<int:id>/', views.update_work_status, name='update_work_status'),
    path('worker_completed_works', views.worker_completed_works, name='worker_completed_works'),
    path('admin_completed_works', views.admin_completed_works, name='admin_completed_works'),
    path('list_completed_work/<int:id>/', views.list_completed_work, name='list_completed_work'),
    path('add_complaints', views.add_complaints, name='add_complaints'),
    path('view_complaints', views.view_complaints, name='view_complaints'),
    path('delete_complaints/<int:id>/', views.delete_complaints, name='delete_complaints'),
    path('admin_view_complaints', views.admin_view_complaints, name='admin_view_complaints'),
    path('complaint_reply/<int:id>/', views.complaint_reply, name='complaint_reply'),
    path('worker_view_complaints', views.worker_view_complaints, name='worker_view_complaints'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('update_user_profile', views.update_user_profile, name='update_user_profile'),
    path('worker_profile', views.worker_profile, name='worker_profile'),
    path('update_worker_profile', views.update_worker_profile, name='update_worker_profile'),
    path('users', views.view_users, name='users'),
    path('service_filter/<int:id>/', views.service_filter, name='service_filter'),
    path('admin_service_filter/<int:id>/', views.admin_service_filter, name='admin_service_filter'),
    path("pay/<int:id>/", views.create_paypal_payment, name='pay'),
    path("payment-success/<int:id>/", views.payment_success, name='success_payment'),
    path("payment-cancel/<int:id>/", views.payment_cancel, name='cancel_payment'),
    path('payment_details/<int:id>/', views.payment_details, name='payment_details'),
    path('admin_payment_details/<int:id>/', views.admin_payment_details, name='admin_payment_details'),
    path('worker_payment_details/<int:id>/', views.worker_payment_details, name='worker_payment_details'),
    path('update_offline_payment/<int:id>/', views.update_offline_payment, name='update_offline_payment'),
    path("worker_pay/<int:id>/", views.create_worker_payout, name='worker_pay'),
    path("worker_wallet", views.worker_wallet, name='worker_wallet'),
    path("admin_wallet", views.completed_payment_details, name='admin_wallet'),

]
